### ISSUE TITLE
Some TLS tests failed with Python 3.11.3

### ISSUE THREAD

**Issue by yan12125** [agronholm/anyio#550]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### AnyIO version

git-master (b38e5995fbf8b38d3c19e3fa6d7aafcdd1c19e76)

### Python version

3.11.3

### What happened?

Some tests failed:
```
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.3.0, pluggy-1.0.0
rootdir: /build/python-anyio/src/anyio
configfile: pyproject.toml
plugins: anyio-3.6.2, hypothesis-6.59.0, mock-3.10.0
collected 26 items

tests/streams/test_tls.py ..FF.....FF..FF.........FF                     [100%]

=================================== FAILURES ===================================
_________________ TestTLSStream.test_extra_attributes[asyncio] _________________
tests/streams/test_tls.py:105: in test_extra_attributes
    assert isinstance(wrapper.extra(TLSAttribute.shared_ciphers), list)
E   assert False
E    +  where False = isinstance(None, list)
E    +    where None = <bound method TypedAttributeProvider.extra of TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object...c987f8d10>, _read_bio=<_ssl.MemoryBIO object at 0x7f0c98f99e70>, _write_bio=<_ssl.MemoryBIO object at 0x7f0c98f99c00>)>(<object object at 0x7f0c9a984f30>)
E    +      where <bound method TypedAttributeProvider.extra of TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object...c987f8d10>, _read_bio=<_ssl.MemoryBIO object at 0x7f0c98f99e70>, _write_bio=<_ssl.MemoryBIO object at 0x7f0c98f99c00>)> = TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x7f0c987f9410>, standard_compatible=False...0c987f8d10>, _read_bio=<_ssl.MemoryBIO object at 0x7f0c98f99e70>, _write_bio=<_ssl.MemoryBIO object at 0x7f0c98f99c00>).extra
E    +      and   <object object at 0x7f0c9a984f30> = TLSAttribute.shared_ciphers
_____________ TestTLSStream.test_extra_attributes[asyncio+uvloop] ______________
tests/streams/test_tls.py:105: in test_extra_attributes
    assert isinstance(wrapper.extra(TLSAttribute.shared_ciphers), list)
E   assert False
E    +  where False = isinstance(None, list)
E    +    where None = <bound method TypedAttributeProvider.extra of TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object...c98893ed0>, _read_bio=<_ssl.MemoryBIO object at 0x7f0c98fa2da0>, _write_bio=<_ssl.MemoryBIO object at 0x7f0c98fa0520>)>(<object object at 0x7f0c9a984f30>)
E    +      where <bound method TypedAttributeProvider.extra of TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object...c98893ed0>, _read_bio=<_ssl.MemoryBIO object at 0x7f0c98fa2da0>, _write_bio=<_ssl.MemoryBIO object at 0x7f0c98fa0520>)> = TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x7f0c98893090>, standard_compatible=False...0c98893ed0>, _read_bio=<_ssl.MemoryBIO object at 0x7f0c98fa2da0>, _write_bio=<_ssl.MemoryBIO object at 0x7f0c98fa0520>).extra
E    +      and   <object object at 0x7f0c9a984f30> = TLSAttribute.shared_ciphers
___________ TestTLSStream.test_ragged_eofs[asyncio-server_standard] ____________
tests/streams/test_tls.py:244: in test_ragged_eofs
    assert isinstance(server_exc, OSError)
E   assert False
E    +  where False = isinstance(None, OSError)
___________ TestTLSStream.test_ragged_eofs[asyncio-client_standard] ____________
tests/streams/test_tls.py:237: in test_ragged_eofs
    with client_cm:
E   Failed: DID NOT RAISE <class 'anyio.BrokenResourceError'>
________ TestTLSStream.test_ragged_eofs[asyncio+uvloop-server_standard] ________
tests/streams/test_tls.py:244: in test_ragged_eofs
    assert isinstance(server_exc, OSError)
E   assert False
E    +  where False = isinstance(None, OSError)
________ TestTLSStream.test_ragged_eofs[asyncio+uvloop-client_standard] ________
tests/streams/test_tls.py:237: in test_ragged_eofs
    with client_cm:
E   Failed: DID NOT RAISE <class 'anyio.BrokenResourceError'>
_________________ TestTLSListener.test_handshake_fail[asyncio] _________________
tests/streams/test_tls.py:411: in test_handshake_fail
    assert isinstance(exception, BrokenResourceError)
E   AssertionError: assert False
E    +  where False = isinstance(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1002)'), BrokenResourceError)
------------------------------ Captured log call -------------------------------
ERROR    anyio.streams.tls:tls.py:286 Error during TLS handshake
NoneType: None
_____________ TestTLSListener.test_handshake_fail[asyncio+uvloop] ______________
tests/streams/test_tls.py:411: in test_handshake_fail
    assert isinstance(exception, BrokenResourceError)
E   AssertionError: assert False
E    +  where False = isinstance(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1002)'), BrokenResourceError)
------------------------------ Captured log call -------------------------------
ERROR    anyio.streams.tls:tls.py:286 Error during TLS handshake
NoneType: None
========================= 8 failed, 18 passed in 1.61s =========================
```

### How can we reproduce the bug?

1. Upgrade to Python 3.11.3
2. Fix incorrectly skipped tests caused by https://github.com/agronholm/anyio/commit/891c0d6fff5b3a77aba682c1479b3f8ccfbc69d6:
```Diff
diff --git a/tests/streams/test_tls.py b/tests/streams/test_tls.py
index fed2b1d..f062763 100644
--- a/tests/streams/test_tls.py
+++ b/tests/streams/test_tls.py
@@ -2,6 +2,7 @@ from __future__ import annotations
 
 import socket
 import ssl
+import sys
 from contextlib import ExitStack
 from threading import Thread
 from typing import ContextManager, NoReturn
@@ -22,7 +23,7 @@ from anyio.streams.tls import TLSAttribute, TLSListener, TLSStream
 
 pytestmark = pytest.mark.anyio
 skip_on_broken_openssl = pytest.mark.skipif(
-    ssl.OPENSSL_VERSION_INFO[0] > 1,
+    (ssl.OPENSSL_VERSION_INFO[0] > 1 and sys.version_info == (3, 7)),
     reason="Python 3.7 does not work with OpenSSL versions higher than 1.X",
 )
 
```
3. Run `pytest tests/streams/test_tls.py`

Those tests do not fail with Python 3.11.2. Probably TLS/SSL changes in 3.11.3 [1][2][3] are relevant.

[1] https://docs.python.org/release/3.11.3/whatsnew/changelog.html#python-3-11-3
[2] https://github.com/python/cpython/pull/95495
[3] https://github.com/python/cpython/pull/96932

**Comment by mweinelt** [comment]
The regression is also visible on 3.10.11.

**Comment by agronholm** [comment]
Yep, I got those too on 3.11.3. I'll try to investigate today.

**Comment by agronholm** [comment]
I'm seeing an inconsistent number of these failures though; got 4 on my first try, 3 on the second. OP seems to be getting 8?

**Comment by mweinelt** [comment]
Saw 12 on aarch64-linux on our build system.

https://hydra.nixos.org/log/lpgimpwq0fs61xnivjhw786lpwjxbhw0-python3.10-anyio-3.5.0.drv

**Comment by yan12125** [comment]
> I'm seeing an inconsistent number of these failures though; got 4 on my first try, 3 on the second. OP seems to be getting 8?

As mentioned in the first comment, on the master branch, some tests are incorrectly skipped due to https://github.com/agronholm/anyio/commit/891c0d6fff5b3a77aba682c1479b3f8ccfbc69d6. As a result, some of broken tests only appear when the patch in the first comment is applied. Sorry if I didn't mention it clearly.

**Comment by agronholm** [comment]
> As mentioned in the first comment, on the master branch, some tests are incorrectly skipped due to [891c0d6](https://github.com/agronholm/anyio/commit/891c0d6fff5b3a77aba682c1479b3f8ccfbc69d6). As a result, some of broken tests only appear when the patch in the first comment is applied. Sorry if I didn't mention it clearly.

Oh, sorry, I missed that. I was a bit tired when looking at this :sweat_smile:

**Comment by agronholm** [comment]
As far as the first failing test goes, it does so consistently on the latest batch of Pythons. The test actually tries to get the list of shared ciphers on the client side, which the documentation (for `SSLSocket`) says would be `None`. Perhaps it just didn't work as advertised until now?

**Comment by agronholm** [comment]
I've corrected the skip condition on master, and it's failing for Python >= 3.10 now. Locally it's passing for all supported Python versions, sans 3.11.3 which I compiled manually. I hate OpenSSL.

**Comment by yan12125** [comment]
> Perhaps it just didn't work as advertised until now?

Yep that seems the case.

**Comment by agronholm** [comment]
I'm modifying the `TLSAttributes.shared_ciphers` attribute to always return `None` when `server_side` is `False`. I'll add another test that reverses the roles, where `shared_ciphers` should return a non-empty list. That should take care of the attribute test failures at least.

**Comment by agronholm** [comment]
The linked PR fixes the inconsistency regarding `TLSAttribute.shared_ciphers`. I'm now working on the handshake failure/ragged EOF test failures which I was only able to reproduce on my Ubuntu 22.04 home server.

**Comment by agronholm** [comment]
I made `SSLZeroReturnError` equal to `SSLEOFError`, and that seems to have fixed the handshake failure tests. However, `test_ragged_eofs` is still failing because the server side is not raising any errors on ragged EOFs. I'm still investigating the cause.

**Comment by yan12125** [comment]
Thanks! Will those fixes be backported to some future 3.6.x version?

**Comment by agronholm** [comment]
I was planning on it. I just need to decide what other fixes I can backport.

**Comment by yan12125** [comment]
Thanks! I managed to cherry-pick the patch onto 3.6.2 tag, but I cannot create a pull request as I didn't find a 3.x branch.
```Diff
diff --git a/src/anyio/streams/tls.py b/src/anyio/streams/tls.py
index c8e19e2..05a70cb 100644
--- a/src/anyio/streams/tls.py
+++ b/src/anyio/streams/tls.py
@@ -37,8 +37,9 @@ class TLSAttribute(TypedAttributeSet):
     peer_certificate_binary: Optional[bytes] = typed_attribute()
     #: ``True`` if this is the server side of the connection
     server_side: bool = typed_attribute()
-    #: ciphers shared between both ends of the TLS connection
-    shared_ciphers: List[Tuple[str, str, int]] = typed_attribute()
+    #: ciphers shared by the client during the TLS handshake (``None`` if this is the
+    #: client side)
+    shared_ciphers: Optional[List[Tuple[str, str, int]]] = typed_attribute()
     #: the :class:`~ssl.SSLObject` used for encryption
     ssl_object: ssl.SSLObject = typed_attribute()
     #: ``True`` if this stream does (and expects) a closing TLS handshake when the stream is being
@@ -105,7 +106,7 @@ class TLSStream(ByteStream):
 
             # Re-enable detection of unexpected EOFs if it was disabled by Python
             if hasattr(ssl, "OP_IGNORE_UNEXPECTED_EOF"):
-                ssl_context.options ^= ssl.OP_IGNORE_UNEXPECTED_EOF  # type: ignore[attr-defined]
+                ssl_context.options &= ~ssl.OP_IGNORE_UNEXPECTED_EOF  # type: ignore[attr-defined]
 
         bio_in = ssl.MemoryBIO()
         bio_out = ssl.MemoryBIO()
@@ -228,7 +229,9 @@ class TLSStream(ByteStream):
                 True
             ),
             TLSAttribute.server_side: lambda: self._ssl_object.server_side,
-            TLSAttribute.shared_ciphers: lambda: self._ssl_object.shared_ciphers(),
+            TLSAttribute.shared_ciphers: lambda: self._ssl_object.shared_ciphers()
+            if self._ssl_object.server_side
+            else None,
             TLSAttribute.standard_compatible: lambda: self.standard_compatible,
             TLSAttribute.ssl_object: lambda: self._ssl_object,
             TLSAttribute.tls_version: self._ssl_object.version,
diff --git a/tests/conftest.py b/tests/conftest.py
index 6ee5a53..5d032be 100644
--- a/tests/conftest.py
+++ b/tests/conftest.py
@@ -54,7 +54,7 @@ def ca() -> CA:
 def server_context(ca: CA) -> SSLContext:
     server_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
     if hasattr(ssl, "OP_IGNORE_UNEXPECTED_EOF"):
-        server_context.options ^= ssl.OP_IGNORE_UNEXPECTED_EOF  # type: ignore[attr-defined]
+        server_context.options &= ~ssl.OP_IGNORE_UNEXPECTED_EOF  # type: ignore[attr-defined]
 
     ca.issue_cert("localhost").configure_cert(server_context)
     return server_context
@@ -64,7 +64,7 @@ def server_context(ca: CA) -> SSLContext:
 def client_context(ca: CA) -> SSLContext:
     client_context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
     if hasattr(ssl, "OP_IGNORE_UNEXPECTED_EOF"):
-        client_context.options ^= ssl.OP_IGNORE_UNEXPECTED_EOF  # type: ignore[attr-defined]
+        client_context.options &= ~ssl.OP_IGNORE_UNEXPECTED_EOF  # type: ignore[attr-defined]
 
     ca.configure_trust(client_context)
     return client_context
diff --git a/tests/streams/test_tls.py b/tests/streams/test_tls.py
index 73ccfad..4d3a263 100644
--- a/tests/streams/test_tls.py
+++ b/tests/streams/test_tls.py
@@ -5,6 +5,7 @@ from threading import Thread
 from typing import ContextManager, NoReturn
 
 import pytest
+from pytest_mock import MockerFixture
 from trustme import CA
 
 from anyio import (
@@ -12,10 +13,13 @@ from anyio import (
     EndOfStream,
     Event,
     connect_tcp,
+    create_memory_object_stream,
     create_task_group,
     create_tcp_listener,
+    to_thread,
 )
 from anyio.abc import AnyByteStream, SocketAttribute, SocketStream
+from anyio.streams.stapled import StapledObjectStream
 from anyio.streams.tls import TLSAttribute, TLSListener, TLSStream
 
 pytestmark = pytest.mark.anyio
@@ -95,7 +99,7 @@ class TestTLSStream:
                     wrapper.extra(TLSAttribute.peer_certificate_binary), bytes
                 )
                 assert wrapper.extra(TLSAttribute.server_side) is False
-                assert isinstance(wrapper.extra(TLSAttribute.shared_ciphers), list)
+                assert wrapper.extra(TLSAttribute.shared_ciphers) is None
                 assert isinstance(wrapper.extra(TLSAttribute.ssl_object), ssl.SSLObject)
                 assert wrapper.extra(TLSAttribute.standard_compatible) is False
                 assert wrapper.extra(TLSAttribute.tls_version).startswith("TLSv")
@@ -368,6 +372,20 @@ class TestTLSStream:
         server_thread.join()
         server_sock.close()
 
+    @pytest.mark.skipif(
+        not hasattr(ssl, "OP_IGNORE_UNEXPECTED_EOF"),
+        reason="The ssl module does not have the OP_IGNORE_UNEXPECTED_EOF attribute",
+    )
+    async def test_default_context_ignore_unexpected_eof_flag_off(
+        self, mocker: MockerFixture
+    ) -> None:
+        send1, receive1 = create_memory_object_stream()
+        client_stream = StapledObjectStream(send1, receive1)
+        mocker.patch.object(TLSStream, "_call_sslobject_method")
+        tls_stream = await TLSStream.wrap(client_stream)
+        ssl_context = tls_stream.extra(TLSAttribute.ssl_object).context
+        assert not ssl_context.options & ssl.OP_IGNORE_UNEXPECTED_EOF
+
 
 class TestTLSListener:
     async def test_handshake_fail(self, server_context: ssl.SSLContext) -> None:
@@ -399,3 +417,74 @@ class TestTLSListener:
             tg.cancel_scope.cancel()
 
         assert isinstance(exception, BrokenResourceError)
+
+    async def test_extra_attributes(
+        self, client_context: ssl.SSLContext, server_context: ssl.SSLContext, ca: CA
+    ) -> None:
+        def connect_sync(addr: tuple[str, int]) -> None:
+            with socket.create_connection(addr) as plain_sock:
+                plain_sock.settimeout(2)
+                with client_context.wrap_socket(
+                    plain_sock,
+                    server_side=False,
+                    server_hostname="localhost",
+                    suppress_ragged_eofs=False,
+                ) as conn:
+                    conn.recv(1)
+                    conn.unwrap()
+
+        class CustomTLSListener(TLSListener):
+            @staticmethod
+            async def handle_handshake_error(
+                exc: BaseException, stream: AnyByteStream
+            ) -> None:
+                await TLSListener.handle_handshake_error(exc, stream)
+                pytest.fail("TLS handshake failed")
+
+        async def handler(stream: TLSStream) -> None:
+            async with stream:
+                try:
+                    assert stream.extra(TLSAttribute.alpn_protocol) == "h2"
+                    assert isinstance(
+                        stream.extra(TLSAttribute.channel_binding_tls_unique), bytes
+                    )
+                    assert isinstance(stream.extra(TLSAttribute.cipher), tuple)
+                    assert isinstance(stream.extra(TLSAttribute.peer_certificate), dict)
+                    assert isinstance(
+                        stream.extra(TLSAttribute.peer_certificate_binary), bytes
+                    )
+                    assert stream.extra(TLSAttribute.server_side) is True
+                    shared_ciphers = stream.extra(TLSAttribute.shared_ciphers)
+                    assert isinstance(shared_ciphers, list)
+                    assert len(shared_ciphers) > 1
+                    assert isinstance(
+                        stream.extra(TLSAttribute.ssl_object), ssl.SSLObject
+                    )
+                    assert stream.extra(TLSAttribute.standard_compatible) is True
+                    assert stream.extra(TLSAttribute.tls_version).startswith("TLSv")
+                finally:
+                    event.set()
+                    await stream.send(b"\x00")
+
+        # Issue a client certificate and make the server trust it
+        client_cert = ca.issue_cert("dummy-client")
+        client_cert.configure_cert(client_context)
+        ca.configure_trust(server_context)
+        server_context.verify_mode = ssl.CERT_REQUIRED
+
+        event = Event()
+        server_context.set_alpn_protocols(["h2"])
+        client_context.set_alpn_protocols(["h2"])
+        listener = await create_tcp_listener(local_host="127.0.0.1")
+        tls_listener = CustomTLSListener(listener, server_context)
+        async with tls_listener, create_task_group() as tg:
+            assert tls_listener.extra(TLSAttribute.standard_compatible) is True
+            tg.start_soon(tls_listener.serve, handler)
+            client_thread = Thread(
+                target=connect_sync,
+                args=[listener.extra(SocketAttribute.local_address)],
+            )
+            client_thread.start()
+            await event.wait()
+            await to_thread.run_sync(client_thread.join)
+            tg.cancel_scope.cancel()
```

**Comment by agronholm** [comment]
I've created a 3.x branches and cherry picked this fixed there.

**Comment by agronholm** [comment]
I want to at least include some form of uncancellation support for Python 3.11 in the upcoming 3.x release. The rest of the fixes are optional, but if they don't give me much trouble, I'll include any that don't break backwards compatibility.
