### ISSUE TITLE
Python 3.11: @asyncio.coroutine test failures

### ISSUE THREAD

**Issue by hroncok** [agronholm/anyio#430]
Hello. On Python 3.11.0a6, the tests fail with `AttributeError: module 'asyncio' has no attribute 'coroutine'`.

To reproduce, temporarily remove uvloop from test extra:

```diff
diff --git a/setup.cfg b/setup.cfg
index 63d5592..153cdbc 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -50,8 +50,6 @@ test =
     pytest >= 7.0
     pytest-mock >= 3.6.1
     trustme
-    uvloop < 0.15; python_version < '3.7' and (platform_python_implementation == 'CPython' and platform_system != 'Windows')
-    uvloop >= 0.15; python_version >= '3.7' and (platform_python_implementation == 'CPython' and platform_system != 'Windows')
 trio = trio >= 0.16
 doc =
     packaging
```

And run:

```
$ tox -re py311 -- -k 'test_wait_generator_based_task_blocked or test_cancel_generator_based_task'
py311 inst-nodeps: .../anyio/.tox/.tmp/package/1/anyio-3.5.0.post2+dirty.tar.gz
py311 installed: anyio @ file://.../anyio/.tox/.tmp/package/1/anyio-3.5.0.post2%2Bdirty.tar.gz,async-generator==1.10,attrs==21.4.0,cffi==1.15.0,coverage==6.3.2,cryptography==36.0.2,hypothesis==6.40.0,idna==3.3,iniconfig==1.1.1,outcome==1.1.0,packaging==21.3,pluggy==1.0.0,py==1.11.0,pycparser==2.21,pyparsing==3.0.7,pytest==7.1.1,pytest-mock==3.7.0,sniffio==1.2.0,sortedcontainers==2.4.0,tomli==2.0.1,trio==0.20.0,trustme==0.9.0
py311 run-test-pre: PYTHONHASHSEED='4277600544'
py311 run-test: commands[0] | coverage run -m pytest -k 'test_wait_generator_based_task_blocked or test_cancel_generator_based_task'
============================= test session starts ==============================
platform linux -- Python 3.11.0a6, pytest-7.1.1, pluggy-1.0.0
cachedir: .tox/py311/.pytest_cache
rootdir: .../anyio, configfile: pyproject.toml, testpaths: tests
plugins: anyio-3.5.0.post2+dirty, mock-3.7.0, hypothesis-6.40.0
collected 1296 items / 1294 deselected / 2 selected

tests/test_debugging.py F                                                [ 50%]
tests/test_taskgroups.py F                                               [100%]

=================================== FAILURES ===================================
____________________ test_wait_generator_based_task_blocked ____________________
tests/test_debugging.py:100: in test_wait_generator_based_task_blocked
    @asyncio.coroutine
E   AttributeError: module 'asyncio' has no attribute 'coroutine'
_______________________ test_cancel_generator_based_task _______________________
tests/test_taskgroups.py:812: in test_cancel_generator_based_task
    from asyncio import coroutine
E   ImportError: cannot import name 'coroutine' from 'asyncio' (/usr/lib64/python3.11/asyncio/__init__.py)
====================== 2 failed, 1294 deselected in 0.42s ======================
ERROR: InvocationError for command .../anyio/.tox/py311/bin/coverage run -m pytest -k 'test_wait_generator_based_task_blocked or test_cancel_generator_based_task' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py311: commands failed
```

I suppose the tests are designed to explicitly test `@asyncio.coroutine` so converting the coroutines to `async def` is not a fix. Should the tests be skipped on 3.11+?

**Comment by hroncok** [comment]
Like this: https://github.com/agronholm/anyio/pull/431

**Comment by agronholm** [comment]
The 4.0 branch works with Python 3.11. Progress has stalled mainly due to a required PR on trio being stalled.

**Comment by hroncok** [comment]
I see. so basically https://github.com/agronholm/anyio/commit/5fbe4effb7b7d3d7c8b80567347f0dd543698b89

**Comment by agronholm** [comment]
Did you get the test suite to pass after your patch?

**Comment by hroncok** [comment]
Yes, in the Fedora build system with patched trio.

**Comment by agronholm** [comment]
Right – trio in its present state doesn't work with 3.11. I have an open [PR](https://github.com/python-trio/trio/pull/2213) that would fix that along with bringing support for exception groups.
